spring:
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}

    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  cache:
    type: none
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true

logging:
  file:
    name: app.log
